fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
#  service:
#    mailer: fos_user.mailer.twig_swift
  from_email:
    address: scshasha@icloud.com
    sender_name: Siv Shasha
  registration:
    confirmation:
      enabled: true