version: '3'

services:
  postgres:
    container_name: ${PROJECT_NAME}_postgres
    build:
      context: ./.docker/database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    build:
      context: ./.docker/nginx
    volumes:
      - ./code:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  php-fpm:
    container_name: ${PROJECT_NAME}_php-fpm
    working_dir: "/code"
    build:
      context: ./.docker/php-fpm
    volumes:
      - ./code:/var/www